import React from "react";
import Head from "next/head";
import Link from "next/link";
import EmojiRain from "@/components/emoji/EmojiRain";
import { Input } from "@/components/ui/input";
import { useDebounceCallback, useTimeout } from "usehooks-ts";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const threadID = React.useRef<string>("");
  const [name, setName] = React.useState("");

  const handleNameInput = (text: string) => {
    setName(text);
  };

  React.useEffect(() => {
    // Generate a unique thread id on first visit
    const randomBytes = crypto.getRandomValues(new Uint8Array(32));
    const uniqueID = Buffer.from(randomBytes).toString("hex");
    threadID.current = uniqueID;
  }, []);

  return (
    <>
      <Head>
        <title>ROAST ME</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <EmojiRain
          emojis={["🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡"]}
        />
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="rainbow-text z-10 text-9xl font-extrabold tracking-tight">
            ROAST ME
          </h1>
          <div className="z-10 flex flex-col gap-4">
            <Input
              className="w-96 bg-transparent text-center text-lg text-gray-400"
              placeholder="What's your name?"
              value={name}
              onChange={(e) => {
                handleNameInput(e.target.value);
              }}
            />
            <Button
              className="bg-transparent text-center text-lg text-gray-400 hover:bg-gray-700 hover:bg-opacity-35 hover:text-gray-400"
              variant={"outline"}
              disabled={name === ""}
              onClick={() => {
                router.replace(`/roast/${threadID.current}?name=${name}`);
              }}
            >
              {name === ""
                ? "Type in your name above broooo"
                : "PLEASE START ROASTING ME"}
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}
