import React from "react";
import Head from "next/head";
import Link from "next/link";
import EmojiRain from "@/components/emoji/EmojiRain";
import { Input } from "@/components/ui/input";
import { useDebounceCallback, useTimeout } from "usehooks-ts";
import { Button } from "@/components/ui/button";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "next/router";
import axios from "axios";
import { env } from "@/env";
import Image from "next/image";

interface RoastData {
  roast: string;
}

export default function Home() {
  const router = useRouter();
  const threadID = React.useRef<string>("");
  const name = React.useRef<string>("");
  const [leftRight, setLeftRight] = React.useState(false);

  const { data, isLoading, refetch } = useQuery<RoastData>({
    queryKey: ["roast", name.current],
    queryFn: async () => {
      const res = await axios
        .get<RoastData>(
          `${env.NEXT_PUBLIC_BACKEND_URL}/roast/${threadID.current}?name=${name.current}`,
        )
        .then((res) => res.data);
      console.log(res.roast);
      return res;
    },
  });

  React.useEffect(() => {
    const nameFromQuery = router.query["name"] as string;
    const idFromQuery = router.query["id"] as string;

    threadID.current = idFromQuery;
    name.current = nameFromQuery;
  }, []);

  return (
    <>
      <Head>
        <title>ROAST ME</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <EmojiRain
          emojis={["🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡", "🤡"]}
        />
        {leftRight ? (
          <div className="container flex flex-row items-center justify-center gap-12 px-4 py-16 ">
            <Image src={"/face1.png"} width={400} height={600} alt="" />
            <div className="speech-bubble relative rounded-lg border-2 p-6 text-8xl text-gray-400">
              {isLoading ? "..." : data?.roast || "You are smelly"}
            </div>
          </div>
        ) : (
          <div className="container flex flex-row items-center justify-center gap-12 px-4 py-16 ">
            <div className="speech-bubble relative rounded-lg border-2 p-6 text-8xl text-gray-400">
              {isLoading ? "..." : data?.roast || "You are smelly"}
            </div>
            <Image
              className="scale-x-[-1]"
              src={"/face1.png"}
              width={400}
              height={600}
              alt=""
            />
          </div>
        )}
        <Button
          className="bg-transparent p-9 text-center text-3xl text-gray-400 hover:bg-gray-700 hover:bg-opacity-35 hover:text-gray-400"
          variant={"outline"}
          onClick={() => {
            refetch();
            setLeftRight((prev) => !prev);
            console.log("refetch");
          }}
        >
          Roast Me Again
        </Button>
      </main>
    </>
  );
}
